### ISSUE TITLE
Need tantalum on aqua?

### ISSUE THREAD

**Issue by StormCmmdr** [Daxillion48/Farborne-Industries#1]
I have beaten plains on Deimo, which I thought was the intended progression. I go back to Erebus to continue that story, only to be told I need tantalum on aqua to go to the shallows? Nit sure that is correct. Playing on Android phone if that is needed.

**Comment by Daxillion48** [comment]
It works just like on erekir. It said aqua bevause it's the nearest sector. Juts go to islands, the sector thta had tantalum, and press planet map. That will make sure you're launching from there. It's not a bug with my mod, rather an oversight in vanilla in the launching system.

**Comment by StormCmmdr** [comment]
I see, I will immediately go back and find the tantalum on islands, didn't even know it was there. Thank you
